FROM node:16.19.0-buster

WORKDIR /app

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

COPY package.json .
COPY packages/ ./packages/
COPY documents/ ./documents/

# runs update in all subdirectories with a package.json
RUN pnpm -r update
RUN pnpm install

EXPOSE 3001
WORKDIR /app/documents

CMD ["pnpm", "start"]