
# FROM node:16.14.0

# RUN mkdir /app
# WORKDIR /app

# RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

# COPY package.json .
# COPY packages/ ./packages/
# COPY services/server/ ./services/server/

# # runs update in all subdirectories with a package.json
# RUN pnpm -r update
# RUN pnpm install

# EXPOSE 8080

# CMD ["pnpm", "start:dev"]
